on:
  push:
    branches:
      - master
name: release
jobs:
  add-changelog:
    name: add-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: "https://registry.npmjs.org"
      - name: Version check
        id: check
        uses: EndBug/version-check@v1.5.0
        with:
          diff-search: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: generate-release-note
        if: steps.check.outputs.changed == 'true'
        run: yarn changelog
      - name: commit-changelog
        if: steps.check.outputs.changed == 'true'
        uses: EndBug/add-and-commit@v4
        with:
          add: "CHANGELOG.md"
          message: "Release ${{ steps.check.outputs.version }}"
          tag: "v${{ steps.check.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
