on:
  push:
    branches:
      - master
name: release
jobs:
  create-release:
    name: add-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: "https://registry.npmjs.org"
      - name: Version check
        id: check
        uses: EndBug/version-check@v1.5.0
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: write-release-note
        if: steps.check.outputs.changed == 'true'
        uses: actions/github-script@v3
        env:
          version: ${{ steps.check.outputs.version }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${process.env.version}`,
              target_commitish: process.env.GITHUB_SHA,
              body: `QAQ`
            });
