name: "Tag test"
on:
  push:
    branches:
      - tag-test

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: add tag
        env:
          TAG_NAME: test
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $TAG_NAME
          git push $(git remote) $TAG_NAME
      - name: check
        run: |
          git tag
